### ISSUE TITLE
Unhandled Exception error

### ISSUE THREAD

**Issue by simon-hall** [sabpprook/HTC_Version_Tool#1]
When I run HTC_Version_Tool.exe on Win7/64bit I get this:

```
HTC Version Tool, code by sabpprook@xda-developers
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at HTC_Version_Tool.Tool.CheckPermission()
   at HTC_Version_Tool.Program.Main(String[] args)

```

...And a GUI popup saying "HTC Version Tool has stopped working".
The problem details shows this:
```
Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	htc_version_tool.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5acc8cb8
  Problem Signature 04:	HTC_Version_Tool
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	5acc8cb8
  Problem Signature 07:	6
  Problem Signature 08:	16
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
```

**Comment by sabpprook** [comment]
It seems ADB did not work on your computer.
Please check if any program/process forced handle ADB server.

**Comment by simon-hall** [comment]
Wow thanks for the quick response :)

adb connects OK:
```
C:\adb>adb devices
List of devices attached
FA67CBN01502    recovery
```

I've tried it with the adb supplied in your zip:
```
C:\adb\htc_version_tool_github>adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as C:\adb\htc_version_tool_github\adb.exe
```

and this one (which I belive is up to date)
```
C:\adb>adb.exe version
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as C:\adb\adb.exe
```
I've also tried on two other PCs (both Win10/64 bit) but always the same results - ?!

Thanks

**Comment by sabpprook** [comment]
Does adb shell work?

```
C:\>adb shell
htc_pmeuhl:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0
htc_pmeuhl:/ $ su
htc_pmeuhl:/ # id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
htc_pmeuhl:/ #
```

**Comment by simon-hall** [comment]
Yes - but it goes straight in as root/su user.

For some reason it also always displays the characters '←[J' when logged in.
```
C:\adb>adb shell
* daemon not running; starting now at tcp:5037
* daemon started successfully
/ # ←[J
/ # id
uid=0 gid=0 groups=1004,1007,1011,1015,1028,3001,3002,3003,3006,3009 context=u:r
:su:s0
/ # su
/sbin/sh: su: not found
/ # id
uid=0 gid=0 groups=1004,1007,1011,1015,1028,3001,3002,3003,3006,3009 context=u:r
:su:s0
```

I have rooted with SuperSU installed via TWRP...

**Comment by sabpprook** [comment]
Could you try this verion?
https://drive.google.com/open?id=1ubjDGNqCfIply-aRN8C7IQNb-YVkD4M7

If still not work, just input command to erase the version

```
C:\>adb shell
htc_pmeuhl:/ $ su
htc_pmeuhl:/ # hexdump -Cn 4096 /dev/block/bootdevice/by-name/misc
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000800  48 54 43 5f 5f 36 32 31  00 ff ff ff ff ff ff ff  |HTC__621........|
00000810  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000820  44 65 76 69 63 65 57 61  72 6d 42 6f 6f 74 00 00  |DeviceWarmBoot..|
00000830  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000850  43 45 20 53 65 72 69 61  6c 20 49 6e 55 73 65 00  |CE Serial InUse.|
00000860  44 65 62 75 67 20 43 61  62 6c 65 20 45 6e 61 00  |Debug Cable Ena.|
00000870  43 45 20 20 20 55 53 42  20 20 49 6e 55 73 65 00  |CE   USB  InUse.|
00000880  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000008a0  32 2e 34 31 2e 37 30 39  2e 37 33 00 00 00 00 00  |2.41.709.73.....|
000008b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000a70  00 00 00 00 46 46 46 46  46 46 46 46 46 46 46 46  |....FFFFFFFFFFFF|
00000a80  46 46 46 46 46 46 46 46  46 46 46 46 46 46 46 46  |FFFFFFFFFFFFFFFF|
*
00000ab0  46 46 46 46 46 46 46 46  00 00 00 00 00 00 00 00  |FFFFFFFF........|
00000ac0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000c20  00 cc aa dd 62 00 00 00  00 00 00 00 00 00 00 00  |....b...........|
00000c30  e2 b3 47 5b 00 00 00 00  00 00 00 00 00 00 00 00  |..G[............|
00000c40  00 08 00 00 59 01 00 00  7e 12 00 00 00 00 00 00  |....Y...~.......|
00000c50  d4 ec 68 58 52 ff 68 58  00 00 00 00 00 00 00 00  |..hXR.hX........|
00000c60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000
htc_pmeuhl:/ # echo -ne '1.00.709.00' | dd of=/dev/block/bootdevice/by-name/misc bs=1 seek=2208 count=16
11+0 records in
11+0 records out
11 bytes transferred in 0.006 secs (1833 bytes/sec)
htc_pmeuhl:/ # hexdump -Cn 4096 /dev/block/bootdevice/by-name/misc
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000800  48 54 43 5f 5f 36 32 31  00 ff ff ff ff ff ff ff  |HTC__621........|
00000810  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000820  44 65 76 69 63 65 57 61  72 6d 42 6f 6f 74 00 00  |DeviceWarmBoot..|
00000830  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000850  43 45 20 53 65 72 69 61  6c 20 49 6e 55 73 65 00  |CE Serial InUse.|
00000860  44 65 62 75 67 20 43 61  62 6c 65 20 45 6e 61 00  |Debug Cable Ena.|
00000870  43 45 20 20 20 55 53 42  20 20 49 6e 55 73 65 00  |CE   USB  InUse.|
00000880  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000008a0  31 2e 30 30 2e 37 30 39  2e 30 30 00 00 00 00 00  |1.00.709.00.....|
000008b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000a70  00 00 00 00 46 46 46 46  46 46 46 46 46 46 46 46  |....FFFFFFFFFFFF|
00000a80  46 46 46 46 46 46 46 46  46 46 46 46 46 46 46 46  |FFFFFFFFFFFFFFFF|
*
00000ab0  46 46 46 46 46 46 46 46  00 00 00 00 00 00 00 00  |FFFFFFFF........|
00000ac0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000c20  00 cc aa dd 62 00 00 00  00 00 00 00 00 00 00 00  |....b...........|
00000c30  e2 b3 47 5b 00 00 00 00  00 00 00 00 00 00 00 00  |..G[............|
00000c40  00 08 00 00 59 01 00 00  7e 12 00 00 00 00 00 00  |....Y...~.......|
00000c50  d4 ec 68 58 52 ff 68 58  00 00 00 00 00 00 00 00  |..hXR.hX........|
00000c60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000
htc_pmeuhl:/ #
```

**Comment by simon-hall** [comment]
I came across that version before - I just guessed that it might be for HTC11 or something.

Anyway - here's the output
```
C:\adb>HTC_Version_Tool.2.exe
##############################################
           HTC Version Tool v2.0
     code by sabpprook@xda-developers
##############################################

Find ADB devices...
-- device mode: Recovery
-- No ROOT or SU permission!
```

Am I correct that my HTC10 must be rooted for HTC_Version_Tool?  I used latest superSU...

**Comment by simon-hall** [comment]
```
C:\adb>adb shell
/ # ←[J
/ # su
/sbin/sh: su: not found
/ # hexdump -Cn 4096 /dev/block/bootdevice/by-name/misc
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000800  48 54 43 5f 5f 30 33 34  00 ff ff ff ff ff ff ff  |HTC__034........|
00000810  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000820  44 65 76 69 63 65 57 61  72 6d 42 6f 6f 74 00 00  |DeviceWarmBoot..|
00000830  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000850  43 45 20 53 65 72 69 61  6c 20 49 6e 55 73 65 00  |CE Serial InUse.|
00000860  44 65 62 75 67 20 43 61  62 6c 65 20 45 6e 61 00  |Debug Cable Ena.|
00000870  43 45 20 20 20 55 53 42  20 20 49 6e 55 73 65 00  |CE   USB  InUse.|
00000880  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000008a0  33 2e 31 36 2e 34 30 31  2e 32 00 00 00 00 00 00  |3.16.401.2......|
000008b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000a70  00 00 00 00 46 46 46 46  46 46 46 46 46 46 46 46  |....FFFFFFFFFFFF|
00000a80  46 46 46 46 46 46 46 46  46 46 46 46 46 46 46 46  |FFFFFFFFFFFFFFFF|
*
00000ab0  46 46 46 46 46 46 46 46  00 00 00 00 00 00 00 00  |FFFFFFFF........|
00000ac0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000c20  11 cc aa dd 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000c30  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000c40  00 08 00 00 0f 0f 0f 0f  fe d7 00 00 00 00 00 00  |................|
00000c50  41 6a 86 56 3f 42 87 56  00 00 00 00 00 00 00 00  |Aj.V?B.V........|
00000c60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000
/ # echo -ne '1.00.709.00' | dd of=/dev/block/bootdevice/by-name/misc bs=1 seek=

2208 count=16
11+0 records in
11+0 records out
11 bytes (11B) copied, 0.040724 seconds, 270B/s
/ # hexdump -Cn 4096 /dev/block/bootdevice/by-name/misc
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000800  48 54 43 5f 5f 30 33 34  00 ff ff ff ff ff ff ff  |HTC__034........|
00000810  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000820  44 65 76 69 63 65 57 61  72 6d 42 6f 6f 74 00 00  |DeviceWarmBoot..|
00000830  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000850  43 45 20 53 65 72 69 61  6c 20 49 6e 55 73 65 00  |CE Serial InUse.|
00000860  44 65 62 75 67 20 43 61  62 6c 65 20 45 6e 61 00  |Debug Cable Ena.|
00000870  43 45 20 20 20 55 53 42  20 20 49 6e 55 73 65 00  |CE   USB  InUse.|
00000880  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000008a0  31 2e 30 30 2e 37 30 39  2e 30 30 00 00 00 00 00  |1.00.709.00.....|
000008b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000a70  00 00 00 00 46 46 46 46  46 46 46 46 46 46 46 46  |....FFFFFFFFFFFF|
00000a80  46 46 46 46 46 46 46 46  46 46 46 46 46 46 46 46  |FFFFFFFFFFFFFFFF|
*
00000ab0  46 46 46 46 46 46 46 46  00 00 00 00 00 00 00 00  |FFFFFFFF........|
00000ac0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000c20  11 cc aa dd 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000c30  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000c40  00 08 00 00 0f 0f 0f 0f  fe d7 00 00 00 00 00 00  |................|
00000c50  41 6a 86 56 3f 42 87 56  00 00 00 00 00 00 00 00  |Aj.V?B.V........|
00000c60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000
/ #
```

Wow - to me that looks like a changing version number :)

Should I now do the same echo... command, with the version number I want?

**Comment by sabpprook** [comment]
Yeah, change the version number you want.

That's weird, I assume that the issue is on computer side.
Anyway, you sort it out finally.

**Comment by simon-hall** [comment]
THANK YOU SO MUCH!  This has been driving me mad for weeks.  Sending internet peace and hugs :)
